name: example
description: Flutter Flow Chart example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_flow_chart:
    path: ../

  # https://pub.dev/packages/star_menu
  star_menu: ^4.0.1

  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.3

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker: ^1.0.3

  # https://pub.dev/packages/file_picker
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
