name: flutter_flow_chart
description: draw a flow chart diagram with different kind of customizable elements. Dashboards can be saved for later use.
version: 1.0.0+1
homepage: https://github.com/alnitak/flutter_flow_chart

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

